version: "3.9"

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    tty: true
    ports:
      - "25565:25565"
      - "25575:25575" # RCON
    environment:
      OPS: "timwm"
      DIFFICULTY: peaceful
      ALLOW_DIFFICULTY: "true"
      EULA: "TRUE"
      VERSION: "1.21"
      TYPE: PAPER
      MODE: creative
      ONLINE_MODE: "false"
      ENFORCE_SECURE_PROFILE: "false"
      RCON_PASSWORD: change-me
      BROADCAST_RCON_TO_OPS: "true"
      LEVEL_TYPE: minecraft:flat
      GENERATOR_SETTINGS: >-
        {
          "layers": [
            { "block": "minecraft:bedrock", "height": 1 },
            { "block": "minecraft:stone",   "height": 124 },
            { "block": "minecraft:dirt",    "height": 2 },
            { "block": "minecraft:grass_block", "height": 1 }
          ],
          "biome": "minecraft:plains"
        }
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "mc-status", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20

  supervisor:
      build: ./supervisor
      container_name: supervisor
      depends_on:
        mc:
          condition: service_healthy
      volumes:
        - ./output:/app/output
      environment:
        BOTS: "Alpha,Bravo"
        TEST: "myTest"
        RECEIVER_PORT_BASE: 8090
      command: >
        python supervisor.py
        --bots Alpha,Bravo
        --test myTest
        --receiver_port_base 8090
      tty: true